name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_parttern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1


      
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        

    #- name: Build Docker Image
      #env:        
        #NEW_VERSION: ${{ steps.version.outputs.version }}
      #run: |
        #docker build -t cryss/practica3.3:$NEW_VERSION .
        #docker build -t cryss/practica3.3:latest .
        
    #- name: Push Docker Image
      #env:
        #NEW_VERSION: ${{ steps.version.outputs.version }}
      #run: |
       #docker push cryss/practica3.3:$NEW_VERSION
       #docker push cryss/practica3.3:latest


    - name: Build and Push Docker Image
      env:        
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64,linux/arm64 -t cryss/practica3.3:$NEW_VERSION --push --load .
        docker buildx build --platform linux/amd64,linux/arm64 -t cryss/practica3.3:latest --push --load .
